### ISSUE TITLE
NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory

### ISSUE THREAD

**Issue by nshthshah** [qmetry/qaf-openapi-support#1]
When I run main method of `com.qmetry.qaf.automation.openapi.v3.CodeGeneratorCLI ` class, I am getting below exception.

```
log4j:WARN No appenders could be found for logger (com.qmetry.qaf.automation.core.ConfigurationManager).
log4j:WARN Please initialize the log4j system properly.
Open API Specifications to process: [http://localhost:8060/v3/api-docs/employee]
Processing: http://localhost:8060/v3/api-docs/employee
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
	at io.swagger.v3.parser.OpenAPIV3Parser.<clinit>(OpenAPIV3Parser.java:37)
	at com.qmetry.qaf.automation.openapi.v3.CodeGeneratorCLI.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 2 more
```

**Comment by nshthshah** [comment]
After adding the below dependencies, the issue gets fixed.

```
<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core -->
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-core</artifactId>
	<version>2.13.1</version>
</dependency>
<dependency>
	<groupId>com.fasterxml.jackson.datatype</groupId>
	<artifactId>jackson-datatype-jsr310</artifactId>
	<version>2.13.1</version>
</dependency>
```
